version: '2'
services:
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bd_iepmae
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/storage:/var/lib/mysql
    command: mysqld --sql_mode=""
  backend:
    image: $IMAGE_DEPLOY
    ports:
      - 80:3000
    container_name: $PROJECT_NAME
    volumes:
      - ./app/:/app
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LC_ALL: en_US.UTF-8
    command: yarn start
